# Generated by Django 2.2 on 2019-06-15 06:28

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='入学日期')),
                ('graduate_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='毕业日期')),
                ('graduate_school', models.CharField(blank=True, default='苏州科技大学', max_length=50, null=True, verbose_name='毕业院校')),
                ('subjects', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='主修课程')),
                ('emphasize', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='突出内容')),
            ],
            options={
                'verbose_name': '教育背景',
                'verbose_name_plural': '教育背景',
            },
        ),
        migrations.CreateModel(
            name='Expection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='职位')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='城市')),
                ('salary', models.CharField(blank=True, max_length=30, null=True, verbose_name='薪资范围')),
                ('duty_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='到岗时间')),
            ],
            options={
                'verbose_name': '期望职业',
                'verbose_name_plural': '期望职业',
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束日期')),
                ('project_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='项目名称')),
                ('project_skills', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目技术')),
                ('tasks', DjangoUeditor.models.UEditorField(default='', verbose_name='项目职责')),
            ],
            options={
                'verbose_name': '项目经验',
                'verbose_name_plural': '项目经验',
            },
        ),
        migrations.CreateModel(
            name='SelfAppraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='自我评价')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], help_text='类目级别', verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '技能类别',
                'verbose_name_plural': '技能类别',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='技能描述')),
                ('skill_level', models.IntegerField(choices=[(1, '了解'), (2, '熟练'), (3, '精通'), (4, '大牛')], default=1, help_text='技能熟练度: 1(了解),2(熟练),3(精通),4(大牛)', verbose_name='熟练程度')),
            ],
            options={
                'verbose_name': '技能特长',
                'verbose_name_plural': '技能特长',
            },
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(blank=True, default=0, null=True, verbose_name='语言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户简历',
                'verbose_name_plural': '用户简历',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束日期')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='任职公司')),
                ('profession', models.CharField(blank=True, max_length=30, null=True, verbose_name='岗位名称')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='部门')),
                ('duty', models.TextField(blank=True, null=True, verbose_name='岗位职责')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='myresume.UserResume', verbose_name='用户')),
            ],
            options={
                'verbose_name': '工作经验',
                'verbose_name_plural': '工作经验',
            },
        ),
    ]
