# Generated by Django 2.2 on 2019-06-15 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myresume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='用户简历'),
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='myresume.SkillCategory', verbose_name='技能类别'),
        ),
        migrations.AddField(
            model_name='skills',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='myresume.UserResume', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父类级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='myresume.SkillCategory', verbose_name='父类级别'),
        ),
        migrations.AddField(
            model_name='selfappraise',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise', to='myresume.UserResume', verbose_name='用户简历'),
        ),
        migrations.AddField(
            model_name='projectexperience',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myresume.UserResume', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='expection',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectation', to='myresume.UserResume', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='myresume.UserResume', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userresume',
            unique_together={('user', 'language')},
        ),
    ]
