# Generated by Django 2.2 on 2019-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_auto_20190615_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='name',
            field=models.CharField(default='我的简历', help_text='简历名称', max_length=200, verbose_name='简历名称'),
        ),
    ]
