# Generated by Django 2.2 on 2019-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_userresume_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expection',
            new_name='Expectation',
        ),
        migrations.AlterField(
            model_name='userresume',
            name='language',
            field=models.IntegerField(blank=True, choices=[(0, '中文'), (1, '英语'), (2, '日语')], default=0, null=True, verbose_name='语言'),
        ),
    ]
