# Generated by Django 2.2 on 2019-06-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_auto_20190615_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='myresume.UserResume', verbose_name='简历ID'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectation', to='myresume.UserResume', verbose_name='简历ID'),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myresume.UserResume', verbose_name='简历ID'),
        ),
        migrations.AlterField(
            model_name='selfappraise',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise', to='myresume.UserResume', verbose_name='简历ID'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='myresume.UserResume', verbose_name='简历ID'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='myresume.UserResume', verbose_name='简历ID'),
        ),
        migrations.AlterUniqueTogether(
            name='userresume',
            unique_together=set(),
        ),
    ]
