# Generated by Django 2.2 on 2019-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0005_auto_20190616_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user/portrait', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='username',
            field=models.CharField(default='姓名', help_text='姓名', max_length=20, verbose_name='姓名'),
        ),
    ]
