# Generated by Django 2.2 on 2019-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0006_auto_20190617_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='duty_time',
            field=models.IntegerField(choices=[(1, '一个月之内'), (2, '两个月之内'), (3, '一周之内')], default=1, help_text='到岗时间: 1(一个月之内),2(两个月之内),3(一周之内)', verbose_name='到岗时间'),
        ),
    ]
