# Generated by Django 2.2 on 2019-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0007_auto_20190617_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectation',
            old_name='salary',
            new_name='salary_max',
        ),
        migrations.AddField(
            model_name='expectation',
            name='salary_min',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='薪资范围'),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='技能标签'),
        ),
    ]
