# Generated by Django 2.2 on 2019-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0009_auto_20190617_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='salary_max',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='最高薪资'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='salary_min',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='最低薪资'),
        ),
        migrations.AlterField(
            model_name='selfappraise',
            name='self_desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='自我评价'),
        ),
    ]
