# Generated by Django 2.2 on 2019-06-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0014_auto_20190620_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexperience',
            name='project_name',
            field=models.CharField(blank=True, default='项目名称', max_length=30, null=True, verbose_name='项目名称'),
        ),
    ]
