# Generated by Django 2.2 on 2019-06-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0015_auto_20190620_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfappraise',
            name='self_desc',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='自我评价'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myresume.SkillCategory', verbose_name='技能类别'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myresume.UserResume', verbose_name='简历ID'),
        ),
    ]
