# Generated by Django 2.2 on 2019-06-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0016_auto_20190621_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfappraise',
            options={'verbose_name': '自我评价', 'verbose_name_plural': '自我评价'},
        ),
        migrations.AlterUniqueTogether(
            name='selfappraise',
            unique_together={('id', 'resume_id')},
        ),
    ]
