# Generated by Django 2.2 on 2019-06-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0017_auto_20190621_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfappraise',
            name='resume_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraise', to='myresume.UserResume', verbose_name='简历ID'),
        ),
    ]
