# Generated by Django 2.2 on 2019-06-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0019_auto_20190621_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfappraise',
            unique_together=set(),
        ),
    ]
