# Generated by Django 2.2 on 2019-06-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0020_auto_20190621_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectation',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='省'),
        ),
    ]
