# Generated by Django 2.2 on 2019-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190531_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userremark',
            name='file',
            field=models.FileField(blank=True, help_text='上传的文件', null=True, upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
