# Generated by Django 2.2 on 2019-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='role',
            field=models.ManyToManyField(related_name='authority', to='user.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='普通用户', max_length=20, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='email',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
    ]
