# Generated by Django 2.2 on 2019-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190616_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
