# Generated by Django 2.2 on 2019-06-19 22:33

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190619_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, help_text='用户头像', null=True, upload_to=user.models.upload_to, verbose_name='用户头像'),
        ),
    ]
